import Head from 'next/head'
import Link from 'next/link';
import { Hero } from '../components/hero/Hero'

import { getAllPublished } from '../lib/notion';
import ResentPost from '../components/resentPosts/ResentPost';

export default function Home({posts}) {
  if(!posts) return <h1>No posts</h1>
  return (
    <div >
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <Hero />

      <ResentPost posts={posts}/>
      </main>
    </div>
  )
}
export const getStaticProps = async () => {
  const data = await getAllPublished()
  return {
    props: {
      posts: data,
    },
    revalidate: 60
  };
};
