import Head from 'next/head'
import { Hero } from '../components/hero/Hero'

import { getAllPublished } from '../lib/notion';
import RecentPost from '../components/recentPosts/RecentPost';

export default function Home({posts}) {
  if(!posts) return <h1>No posts</h1>

  let PostsToShow = posts.slice(0, 3)
  return (
    <div >
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <Hero />

      <RecentPost posts={PostsToShow}/>
      </main>
    </div>
  )
}
export const getStaticProps = async () => {
  const data = await getAllPublished()
  return {
    props: {
      posts: data,
    },
    revalidate: 60
  };
};
